# Generated by Django 5.2.9 on 2026-01-28 09:19

import apps.ducks.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number_of_ducks', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, verbose_name='Notes')),
                ('started_date', models.DateField(default=apps.ducks.models.today)),
                ('culled_date', models.DateField(blank=True, null=True)),
                ('is_culled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Flocks',
                'ordering': ['started_date'],
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField(default=apps.ducks.models.today)),
                ('harvested', models.PositiveBigIntegerField(default=0)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('mortality', models.PositiveBigIntegerField(default=0)),
                ('feed_consumed', models.FloatField(default=0.0, help_text='Feed consumed (sacks)')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='ducks.flock')),
            ],
            options={
                'verbose_name_plural': 'Stats',
                'ordering': ['day'],
            },
        ),
    ]
