# Generated by Django 5.2.9 on 2026-02-18 07:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ducks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flock',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
